language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test
scala:
  - 2.11.0-SNAPSHOT
jdk:
  - openjdk6
notifications:
  email:
    - adriaan@typesafe.com

# if we get weird timeouts, see https://github.com/spray/spray/pull/233
# 'set concurrentRestrictions in Global += Tags.limit(Tags.Test, 1)'
